# name: build_docker

# on:
#   push:
#     branches: [main]
#   release:
#     types: [created] # 当创建新的 Release 时触发

# jobs:
#   build_docker:
#     name: Build docker
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Login to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Build and push
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           platforms: linux/amd64
#           tags: |
#             ${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-sjtu:${{ github.sha }}
#             ${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-sjtu:latest


# name: ApacheBench Test
# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2
      
#     - name: Install ApacheBench
#       run: |
#         sudo apt-get update
#         sudo apt-get install -y apache2-utils
      
#     - name: Run ApacheBench
#       run: ab -n 10000 -c 64 https://gpttell.me/google-fonts/css2?family=Noto+Sans+SC:wght@300;400;700;900&display=swap


name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install asyncio aiohttp
    - name: Download and run script
      run: |
        curl https://gist.githubusercontent.com/olixu/2513bc23e57974aaca14d711e48db96b/raw/017a35f7821618ba851f421659a8e2f11795eec3/gistfile1.txt > test.py
        python test.py









