name: build_docker

on:
  push:
    branches: [main]
  release:
    types: [created] # 当创建新的 Release 时触发

jobs:
  build_docker:
    name: Build docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '20'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          node-version: '20'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          node-version: '20'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          node-version: '20'

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-sjtu:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/sharelatex-sjtu:latest
          node-version: '20'
